//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int PetID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Type { get; set; }
        public byte[] Photo { get; set; }
        public bool IsFixed { get; set; }
        public int SurgeryID { get; set; }
        public int VaccinationID { get; set; }
        public int WeightID { get; set; }
        public int DocumentID { get; set; }
        public int VisitID { get; set; }
        public int ImageID { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Image Image { get; set; }
        public virtual Surgery Surgery { get; set; }
        public virtual Vaccination Vaccination { get; set; }
        public virtual Visit Visit { get; set; }
        public virtual Weight Weight { get; set; }
    }
}
